### ISSUE TITLE
 node-sass@3.13.1 postinstall: `node scripts/build.js`:

### ISSUE THREAD

**Issue by faizanalvi** [faizanalvi/Afsevenscores-theme#1]
PS C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev> npm install gulp-sass --save-dev

> node-sass@3.13.1 install C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\xampp\\htdocs\\afsevenscores\\wordpress\\wp-content\\themes\\gulp-dev\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\xampp\\htdocs\\afsevenscores\\wordpress\\wp-content\\themes\\gulp-dev\\node_modules\\which\\which.js:13:12)\n    at F (C:\\xampp\\htdocs\\afsevenscores\\wordpress\\wp-content\\themes\\gulp-dev\\node_modules\\which\\which.js:68:19)\n    at E (C:\\xampp\\htdocs\\afsevenscores\\wordpress\\wp-content\\themes\\gulp-dev\\node_modules\\which\\which.js:80:29)\n    at C:\\xampp\\htdocs\\afsevenscores\\wordpress\\wp-content\\themes\\gulp-dev\\node_modules\\which\\which.js:89:16\n    at C:\\xampp\\htdocs\\afsevenscores\\wordpress\\wp-content\\themes\\gulp-dev\\node_modules\\isexe\\index.js:42:5\n    at C:\\xampp\\htdocs\\afsevenscores\\wordpress\\wp-content\\themes\\gulp-dev\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python27\python.EXE
gyp verb check python version `C:\Python27\python.EXE -c "import platform; print(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.11.1
gyp verb command install [ '8.11.1' ]
gyp verb install input version string "8.11.1"
gyp verb install installing version: 8.11.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.11.1
gyp verb build dir attempting to create "build" dir: C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-sass\build
gyp verb build dir "build" dir needed to be created? C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-sass\build
gyp verb Not using VS2017: Could not use PowerShell to find VS2017
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-sass\build\config.gypi
gyp verb config.gypi checking for gypi file: C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-sass\config.gypi
gyp verb common.gypi checking for gypi file: C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-sass\common.gypi
gyp verb gyp gyp format was not specified; forcing "msvs"
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\xampp\\htdocs\\afsevenscores\\wordpress\\wp-content\\themes\\gulp-dev\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\xampp\\htdocs\\afsevenscores\\wordpress\\wp-content\\themes\\gulp-dev\\node_modules\\node-sass\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\xampp\\htdocs\\afsevenscores\\wordpress\\wp-content\\themes\\gulp-dev\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Alvih\\.node-gyp\\8.11.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Alvih\\.node-gyp\\8.11.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\xampp\\htdocs\\afsevenscores\\wordpress\\wp-content\\themes\\gulp-dev\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Alvih\\.node-gyp\\8.11.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\xampp\\htdocs\\afsevenscores\\wordpress\\wp-content\\themes\\gulp-dev\\node_modules\\node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\xampp\\htdocs\\afsevenscores\\wordpress\\wp-content\\themes\\gulp-dev\\node_modules\\node-sass\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir C:\Users\Alvih\.node-gyp\8.11.1
gyp verb found first Solution file build/binding.sln
gyp verb could not find "msbuild.exe" in PATH - finding location in registry
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 4/29/2018 2:45:46 AM.
Project "C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-sass\build\binding.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the locat
ion of the component to the system path if it is installed elsewhere.  [C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-sass\build\binding.sln]
Done Building Project "C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-sass\build\binding.sln" (default targets) -- FAILED.

Build FAILED.

"C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-sass\build\binding.sln" (default target) (1) ->
(_src_\libsass target) ->
  MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the loc
ation of the component to the system path if it is installed elsewhere.  [C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-sass\build\binding.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.78
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\afsevenscores\\wordpress\\wp-content\\themes\\gulp-dev\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev\node_modules\node-sass
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alvih\AppData\Roaming\npm-cache\_logs\2018-04-28T21_45_50_154Z-debug.log
PS C:\xampp\htdocs\afsevenscores\wordpress\wp-content\themes\gulp-dev>

**Comment by faizanalvi** [comment]
GitHub everything is Working but i still couldn't  figure it out that what is the exact problem here.

**Comment by AlirezaEbrahimkhani** [comment]
try this it works for me 
`npm install node-sass`
`npm install --ignore-scripts`
`bower install`
`npm install`

or this 
`npm install node-sass@latest`
